### ISSUE TITLE
Recompiling for thread-safety

### ISSUE THREAD

**Issue by randyzwitch** [quinnj/DecFPBuilder#12]
Ref: https://github.com/JuliaMath/DecFP.jl/issues/39#issuecomment-573170555

Per the other thread, it appears that we can make DecFP.jl thread-safe through a compiler flag. Now that 1.3 is out with the threading functionality, this will start to lead to more silent-ish errors unless we fix it.

**Comment by jmkuhn** [comment]
I'd like to make a PR for this issue.  Should I make the PR here or create a build script in Yggdrasil.jl?

**Comment by quinnj** [comment]
Yes, let's move it to a proper Yggrdasil.jl repo/build script.

**Comment by randyzwitch** [comment]
@jmkuhn when you submit that PR, please link back to here, and I'll close this issue

**Comment by giordano** [comment]
https://github.com/JuliaPackaging/Yggdrasil/pull/589

**Comment by jmkuhn** [comment]
Yes, I was planning to once everything was merged.  Here is the current status:
Yggdrasil build script https://github.com/JuliaPackaging/Yggdrasil/pull/589
DecFP_jll https://github.com/JuliaBinaryWrappers/DecFP_jll.jl
DecFP PR https://github.com/JuliaMath/DecFP.jl/pull/106
