### ISSUE TITLE
Use bash array for flags

### ISSUE THREAD

**Issue by simonbyrne** [quinnj/DecFPBuilder#9]
From Slack:

> Yeah; I suggest making a `FLAGS` bash array and incrementally building those flags up with conditionals; it’s the best way we have to create a cross-platform bash script, unfortuantely.
>
> here’s an extreme example
>
> https://github.com/JuliaPackaging/Yggdrasil/blob/master/OpenBLAS/build_tarballs.jl#L32-L47
> 
> By creating a `FLAGS` bash array, then passing it to `make` via something like `make "${flags[@]}" -j${nproc}` you can make this much easier to maintain

**Comment by jmkuhn** [comment]
I implemented a simpler version of this in https://github.com/quinnj/DecFPBuilder/pull/10 using a string variable instead of a bash array.
```
FLAGS="-some -flags"
if [[ $target == "t1" ]]; then
    FLAGS+=" -t1flags"
elif [[ $target == "t2" ]]; then
    FLAGS+=" -t2flags"
fi
```
